import { mkdir, writeFile } from "node:fs/promises"
import path from "node:path"
import { readEntries } from "./knowledge-store"
// KnowledgeEntry type flows through readEntries() return type

const MIN_CONFIDENCE = 0.80

interface GenerateOptions {
  storePath: string
  outputDir: string
  minConfidence?: number
}

/**
 * Generate a CLAUDE.md file from the knowledge store.
 * This is the slow loop's primary output — learned knowledge becomes
 * a file consumed natively by Claude Code in future sessions.
 */
export async function generateClaudeMd(options: GenerateOptions): Promise<string> {
  const { storePath, outputDir, minConfidence = MIN_CONFIDENCE } = options

  const allEntries = await readEntries(storePath)
  const active = allEntries.filter(
    (e) => !e.supersededBy && e.confidence >= minConfidence,
  )

  const rules = active.filter((e) => e.type === "rule")
  const preferences = active.filter((e) => e.type === "preference")
  const procedures = active.filter((e) => e.type === "procedure")
  const facts = active.filter((e) => e.type === "fact")

  const sections: string[] = []
  sections.push("# Project Knowledge (Auto-Generated by Galatea)")
  sections.push("")
  sections.push("> This file is generated from learned knowledge. Do not edit manually.")
  sections.push("")

  if (rules.length > 0) {
    sections.push("## Rules")
    sections.push("")
    for (const rule of rules) {
      sections.push(`- ${rule.content}`)
    }
    sections.push("")
  }

  if (preferences.length > 0) {
    sections.push("## Preferences")
    sections.push("")
    for (const pref of preferences) {
      sections.push(`- ${pref.content}`)
    }
    sections.push("")
  }

  if (procedures.length > 0) {
    sections.push("## Procedures")
    sections.push("")
    for (const proc of procedures) {
      sections.push(`### ${extractTitle(proc.content)}`)
      sections.push("")
      sections.push(proc.content)
      sections.push("")
    }
  }

  if (facts.length > 0) {
    sections.push("## Facts")
    sections.push("")

    // Group by about.entity, ungrouped last
    const grouped = new Map<string, typeof facts>()
    const ungrouped: typeof facts = []
    for (const fact of facts) {
      if (fact.about?.entity) {
        const key = fact.about.entity
        const bucket = grouped.get(key) ?? []
        bucket.push(fact)
        grouped.set(key, bucket)
      } else {
        ungrouped.push(fact)
      }
    }

    for (const [entity, bucket] of grouped) {
      sections.push(`### ${entity.charAt(0).toUpperCase() + entity.slice(1)}`)
      sections.push("")
      for (const fact of bucket) {
        sections.push(`- ${fact.content}`)
      }
      sections.push("")
    }

    if (ungrouped.length > 0) {
      if (grouped.size > 0) {
        sections.push("### General")
        sections.push("")
      }
      for (const fact of ungrouped) {
        sections.push(`- ${fact.content}`)
      }
      sections.push("")
    }
  }

  const md = sections.join("\n")

  await mkdir(outputDir, { recursive: true })
  await writeFile(path.join(outputDir, "CLAUDE.md"), md)

  return md
}

interface SkillFileResult {
  filename: string
  title: string
}

const SKILL_MIN_CONFIDENCE = 0.85

export async function generateSkillFiles(options: GenerateOptions): Promise<SkillFileResult[]> {
  const { storePath, outputDir, minConfidence = SKILL_MIN_CONFIDENCE } = options

  const allEntries = await readEntries(storePath)
  const procedures = allEntries.filter(
    (e) => !e.supersededBy && e.type === "procedure" && e.confidence >= minConfidence,
  )

  if (procedures.length === 0) return []

  const skillsDir = path.join(outputDir, "skills")
  await mkdir(skillsDir, { recursive: true })

  const results: SkillFileResult[] = []

  for (const proc of procedures) {
    const title = extractTitle(proc.content)
    const slug = slugify(title)
    const filename = `${slug}.md`

    const content = [
      `# ${title}`,
      "",
      `> Auto-generated skill from learned procedure (confidence: ${proc.confidence.toFixed(2)})`,
      "",
      proc.content,
      "",
    ].join("\n")

    await writeFile(path.join(skillsDir, filename), content)
    results.push({ filename, title })
  }

  return results
}

interface SubagentResult {
  filename: string
  name: string
}

interface SubagentOptions extends GenerateOptions {
  minProcedures?: number
}

/**
 * Generate subagent definitions from clusters of related procedures.
 * Groups procedures by common prefix (e.g., "Review PR: ..." -> code-reviewer agent).
 */
export async function generateSubagentDefinitions(options: SubagentOptions): Promise<SubagentResult[]> {
  const { storePath, outputDir, minProcedures = 3, minConfidence = SKILL_MIN_CONFIDENCE } = options

  const allEntries = await readEntries(storePath)
  const procedures = allEntries.filter(
    (e) => !e.supersededBy && e.type === "procedure" && e.confidence >= minConfidence,
  )

  // Group by common prefix (first 2 words)
  const groups = new Map<string, typeof procedures>()
  for (const proc of procedures) {
    const prefix = proc.content.split(/[\s:]+/).slice(0, 2).join(" ").toLowerCase()
    const existing = groups.get(prefix) ?? []
    existing.push(proc)
    groups.set(prefix, existing)
  }

  const results: SubagentResult[] = []
  const agentsDir = path.join(outputDir, "agents")

  for (const [prefix, procs] of groups) {
    if (procs.length < minProcedures) continue

    await mkdir(agentsDir, { recursive: true })

    const agentName = slugify(prefix)
    const filename = `${agentName}.md`

    const isReviewAgent = prefix.includes("review")
    const allowedTools = isReviewAgent
      ? ["Read", "Grep", "Glob", "WebSearch"]
      : undefined

    const lines = [
      `# ${prefix.charAt(0).toUpperCase() + prefix.slice(1)} Agent`,
      "",
      `> Auto-generated subagent from ${procs.length} learned procedures`,
      "",
    ]

    if (allowedTools) {
      lines.push(`**Allowed tools:** ${allowedTools.join(", ")}`)
      lines.push("")
    }

    lines.push("## Procedures")
    lines.push("")
    for (const proc of procs) {
      lines.push(`- ${proc.content}`)
    }
    lines.push("")

    await writeFile(path.join(agentsDir, filename), lines.join("\n"))
    results.push({ filename, name: agentName })
  }

  return results
}

function extractTitle(content: string): string {
  // Match sentence-ending punctuation: period followed by space+uppercase (not abbreviations like e.g.)
  const sentenceEnd = content.search(/[!?]|(?<=[a-z\d])\.\s+[A-Z]/)
  const firstSentence =
    sentenceEnd > 0 ? content.slice(0, sentenceEnd).trim() : content.trim()
  if (firstSentence.length <= 80) return firstSentence
  // Fallback: truncate at word boundary
  const truncated = content.slice(0, 80)
  const lastSpace = truncated.lastIndexOf(" ")
  return (lastSpace > 40 ? truncated.slice(0, lastSpace) : truncated) + "…"
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60)
}
