/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as ChatSessionIdRouteImport } from './routes/chat/$sessionId'
import { Route as AgentTraceRouteImport } from './routes/agent/trace'
import { Route as AgentKnowledgeRouteImport } from './routes/agent/knowledge'
import { Route as AgentConfigRouteImport } from './routes/agent/config'
import { Route as AgentChatRouteImport } from './routes/agent/chat'
import { Route as AgentAuditRouteImport } from './routes/agent/audit'
import { Route as AgentExportRouteImport } from './routes/agent/export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTraceRoute = AgentTraceRouteImport.update({
  id: '/agent/trace',
  path: '/agent/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentKnowledgeRoute = AgentKnowledgeRouteImport.update({
  id: '/agent/knowledge',
  path: '/agent/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentConfigRoute = AgentConfigRouteImport.update({
  id: '/agent/config',
  path: '/agent/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentChatRoute = AgentChatRouteImport.update({
  id: '/agent/chat',
  path: '/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAuditRoute = AgentAuditRouteImport.update({
  id: '/agent/audit',
  path: '/agent/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentExportRoute = AgentExportRouteImport.update({
  id: '/agent/export',
  path: '/agent/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent/audit': typeof AgentAuditRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/export': typeof AgentExportRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/agent/trace': typeof AgentTraceRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent/audit': typeof AgentAuditRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/export': typeof AgentExportRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/agent/trace': typeof AgentTraceRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/agent': typeof AgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent/audit': typeof AgentAuditRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/export': typeof AgentExportRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/agent/trace': typeof AgentTraceRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent/audit'
    | '/agent/chat'
    | '/agent/config'
    | '/agent/export'
    | '/agent/knowledge'
    | '/agent/trace'
    | '/chat/$sessionId'
    | '/agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent/audit'
    | '/agent/chat'
    | '/agent/config'
    | '/agent/export'
    | '/agent/knowledge'
    | '/agent/trace'
    | '/chat/$sessionId'
    | '/agent'
  id:
    | '__root__'
    | '/'
    | '/agent/audit'
    | '/agent/chat'
    | '/agent/config'
    | '/agent/export'
    | '/agent/knowledge'
    | '/agent/trace'
    | '/chat/$sessionId'
    | '/agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentAuditRoute: typeof AgentAuditRoute
  AgentChatRoute: typeof AgentChatRoute
  AgentConfigRoute: typeof AgentConfigRoute
  AgentExportRoute: typeof AgentExportRoute
  AgentKnowledgeRoute: typeof AgentKnowledgeRoute
  AgentTraceRoute: typeof AgentTraceRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/trace': {
      id: '/agent/trace'
      path: '/agent/trace'
      fullPath: '/agent/trace'
      preLoaderRoute: typeof AgentTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/knowledge': {
      id: '/agent/knowledge'
      path: '/agent/knowledge'
      fullPath: '/agent/knowledge'
      preLoaderRoute: typeof AgentKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/config': {
      id: '/agent/config'
      path: '/agent/config'
      fullPath: '/agent/config'
      preLoaderRoute: typeof AgentConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/audit': {
      id: '/agent/audit'
      path: '/agent/audit'
      fullPath: '/agent/audit'
      preLoaderRoute: typeof AgentAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/chat': {
      id: '/agent/chat'
      path: '/agent/chat'
      fullPath: '/agent/chat'
      preLoaderRoute: typeof AgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/export': {
      id: '/agent/export'
      path: '/agent/export'
      fullPath: '/agent/export'
      preLoaderRoute: typeof AgentExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentAuditRoute: AgentAuditRoute,
  AgentChatRoute: AgentChatRoute,
  AgentConfigRoute: AgentConfigRoute,
  AgentExportRoute: AgentExportRoute,
  AgentKnowledgeRoute: AgentKnowledgeRoute,
  AgentTraceRoute: AgentTraceRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
  AgentIndexRoute: AgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
